# Config file for Powerlevel10k with the style of robbyrussell theme from Oh My Zsh.
#
# Original: https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#robbyrussell.
#
#LA REPLICACIÓN DEL TEMA DE ROBBYRUSSELL ES EXACTA. LA ÚNICA DIFERENCIA OBSERVABLE ESTÁ EN
#RENDIMIENTO. EL INDICADOR DE POWERLEVEL10K ES MUY RÁPIDO EN TODAS PARTES, INCLUSO EN GRANDES REPOSITORIOS DE GIT
#USO: OBTENGA ESTE ARCHIVO ANTES O DESPUÉS DE CARGAR POWERLEVEL10K 
#   source ~/powerlevel10k/config/p10k-robbyrussell.zsh
#   source ~/powerlevel10k/powerlevel10k.zsh-theme

#CAMBIAR OPCIONES TEMPORALMENTE 
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  #DESACTIVAR TODAS LAS OPCIONES DE CONFIGURACIÓN
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  #SE REQUIERE ZSH >= 5.1.
  autoload -Uz is-at-least && is-at-least 5.1 || return

  #SEGMENTOS DE PROMPT A LA IZQUIERDA
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(prompt_char vcs)
  #SEGMENTOS DE PROMPT A LA DERECHA
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

  #OPCIONES DE ESTILO BÁSICO QUE DEFINEN EL ASPECTO GENERAL DEL PROMPT
  typeset -g POWERLEVEL9K_BACKGROUND=                            # FONDO TRANSPARENTE
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=  # SIN ESPACIOS EN BLANCO CIRCUNDANTES 
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '  # SEGMENTOS SEPARADOS CON UN ESPACIO
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=        # SIN SÍMBOLO DE FIN DE LÍNEA
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=           # no segment icons

  #SÍMBOLO DE PROMPT VERDE SI EL ÚLTIMO COMANDO TUVO ÉXITO
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=green
  #SÍMBOLO DE PROMPT ROJO SI EL ÚLTIMO COMANDO FALLÓ
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=red
  #PROMPT RÁPIDO: FLECHA EN NEGRITA
  typeset -g POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION='%F{red}%n%f%F{white}%m%f %F{red}%~%f  '

  #DIRECTORIO ACTUAL CIAN
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=cyan
  #MUESTRA SOLO EL ÚLTIMO SEGMENTO DEL DIRECTORIO ACTUAL
  #typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
  #DIRECTORIO EN NEGRITA
  #typeset -g POWERLEVEL9K_DIR_CONTENT_EXPANSION='%B$P9K_CONTENT'

  #FORMATEADOR DE GIT STATUS 
  function my_git_formatter() {
    emulate -L zsh
    if [[ -n $P9K_CONTENT ]]; then
      #SI P9K_CONTENT NO ESTÁ VACÍO, ESTÁ "CARGANDO" O DESDE VCS_INFO (NO DESDE EL COMPLEMENTO GITSTATUS). LOS PARÁMETROS VCS_STATUS_* NO ESTÁN DISPONIBLES EN ESTE CASO
      typeset -g my_git_format=$P9K_CONTENT
    else
      #USE LOS PARÁMETROS VCS_STATUS_* PARA ENSAMBLAR EL ESTADO DE GIT. VER REFERENCIA
      # https://github.com/romkatv/gitstatus/blob/master/gitstatus.plugin.zsh.
      typeset -g my_git_format="${1+%B%4F}git:(${1+%1F}"
      my_git_format+=${${VCS_STATUS_LOCAL_BRANCH:-${VCS_STATUS_COMMIT[1,8]}}//\%/%%}
      my_git_format+="${1+%4F})"
      if (( VCS_STATUS_NUM_CONFLICTED || VCS_STATUS_NUM_STAGED ||
            VCS_STATUS_NUM_UNSTAGED   || VCS_STATUS_NUM_UNTRACKED )); then
        my_git_format+=" ${1+%3F}✗"
      fi
    fi
  }
  functions -M my_git_formatter 2>/dev/null

  #DESHABILITAR EL FORMATO PREDETERMINADO DE GIT STATUS
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
  #INSTALE SU PROPIO FORMATEADOR DE GIT STATUS
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter(1)))+${my_git_format}}'
  typeset -g POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION='${$((my_git_formatter()))+${my_git_format}}'
  #ESTADO GRIS DE GIT STATUS AL CARGAR
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=246

  #MODO DE PROMPT INSTANTÁNEO
  # - off: DESHABILITAR PROMPT INSTANTÁNEO. ELIJA ESTO SI PROBÓ EL PROMPT INSTANTÁNEO Y ENCONTRÓ QUE ES INCOMPATIBLE CON SUS ARCHIVOS DE CONFIGURACIÓN ZSH
  # -quiet: HABILITE EL PROMPT INSTANTÁNEO Y NO IMPRIMA ADVERTENCIAS AL DETECTAR LA SALIDA DE LA CONSOLA DURANTE LA INICIALIZACIÓN DE ZSH. ELIJA ESTO SI HA LEÍDO Y ENTENDIDO
  # https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt.
  # -verbose: HABILITE EL PROMPT INSTANTÁNEO E IMPRIMA UNA ADVERTENCIA AL DETECTAR LA SALIDA DE LA CONSOLA DURANTE
  # zsh initialization. ELIJA ESTO SI NUNCA HA PROBADO EL PROMPT INSTANTÁNEO, NO LO HA HECHO
  # VISTO LA ADVERTENCIA, O SI NO ESTÁ SEGURO DE QUÉ SIGNIFICA TODO ESTO
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  # LA RECARGA EN CALIENTE LE PERMITE CAMBIAR LAS OPCIONES DE POWERLEVEL9K DESPUÉS DE QUE SE HAYA INICIALIZADO POWERLEVEL10K
  # POR EJEMPLO, PUEDE ESCRIBIR POWERLEVEL9K_BACKGROUND=red Y VER QUE SU INDICADOR SE VUELVE ROJO
  # RECARGA CALIENTE PUEDE RALENTIZAR EL INDICADOR EN 1-2 MILISEGUNDOS, POR LO QUE ES MEJOR MANTENERLO APAGADO A MENOS QUE REALMENTE LO NECESITE 
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # SI P10K YA ESTÁ CARGADO, VUELVA A CARGAR LA CONFIGURACIÓN
   # ESTO FUNCIONA INCLUSO CON POWERLEVEL9K_DISABLE_HOT_RELOAD=TRUE 
  (( ! $+functions[p10k] )) || p10k reload
}

#DILE A `P10K CONFIGURE` QUÉ ARCHIVO DEBE SOBRESCRIBIR
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
