#!/usr/bin/env bash

if [ "$(id -u)" -eq "0" ]; then

pacman -Syu  --noconfirm

clear

else

echo  ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> "
echo  "> ███╗░░██╗░█████╗░  ██████╗░░█████╗░░█████╗░████████╗  < "
echo  "> ████╗░██║██╔══██╗  ██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝  < "
echo  "> ██╔██╗██║██║░░██║  ██████╔╝██║░░██║██║░░██║░░░██║░░░  < "
echo  "> ██║╚████║██║░░██║  ██╔══██╗██║░░██║██║░░██║░░░██║░░░  < "
echo  "> ██║░╚███║╚█████╔╝  ██║░░██║╚█████╔╝╚█████╔╝░░░██║░░░  < "
echo  "> ╚═╝░░╚══╝░╚════╝░  ╚═╝░░╚═╝░╚════╝░░╚════╝░░░░╚═╝░░░  < "
echo  ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> "

sleep 1

clear

exit

fi

# Definir variables
FOLD_SHARE="/usr/share"
USER_HOME="/home/$USER"
REPO_DIR="$USER_HOME/wmarch"
ROFI_DIR="$USER_HOME/.config/rofi"
ICONS_DIR="$FOLD_SHARE/icons"
THEMES_DIR="$FOLD_SHARE/themes"
LOCAL_DIR="$USER_HOME/.local/share"
CONFIG_DIR="$USER_HOME/.config"
LOCKER_DIR="$LOCAL_DIR/i3lock"
APPLICATIONS_DIR="$FOLD_SHARE/applications"
FSTAB_FILE="/etc/"
WALL_DIR="$FOLD_SHARE/icons/hicolor/16x16/apps/"
FONT_DIR="$FOLD_SHARE/fonts"
POLYBAR_PKG="polybar-git-3.6.3.r45.g1ee11f7c-1-x86_64.pkg.tar.zst"
BROWSE="FIREFOX"
LOG_MANA="LIGHTDM"

# Funciones
function print_status {
    echo -e "\033[1;92m$1\033[0m"
}

ins_browser() {
    print_status "\n\t\t\t\t INSTALANDO $BROWSE"
    pacman -S --needed firefox --noconfirm
    sleep 2
    clear
}

ins_logman() {
    print_status "\n\t\t\t\t INSTALANDO $LOG_MANA"
    pacman -S --needed lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings accountsservice  --noconfirm
    systemctl enable lightdm
    sleep 2
    clear
}

check_plugins() {
    print_status "\n\t\t\t\t COMPROBANDO PLUGINS DE ZSH"
    if [[ -d $FOLD_SHARE/zsh/plugins/zsh-syntax-highlighting/ && -d $FOLD_SHARE/zsh/plugins/zsh-autosuggestions/ ]]; then
    sleep 2
    clear    
    print_status "\n\t\t\t\t YA EXISTEN LAS CARPETAS DE PLUGINS DE ZSH"
    else
    sleep 2
    clear    
    print_status "\n\t\t\t\t NO EXISTE LA CARPETA DE ZSH"
    sleep 2
    clear    
    print_status "\n\t\t\t INSTALANDO ZSH Y COMPLEMENTOS DE ZSH"
    pacman -S --needed zsh zsh-completions zsh-syntax-highlighting zsh-autosuggestions --noconfirm   
    fi
    sleep 2
    clear
}

create_common_dirs() {
    print_status "\n\t\t\t\t CREANDO CARPETAS COMUNES"
    mkdir -pv $USER_HOME/{desc,plant,mus,captura}
    sleep 2
    clear
}

add_dotfiles() {
    print_status "\n\t\t\t\t AGREGANDO DOTFILES"
    mkdir -pv $WALL_DIR
    cp -r $REPO_DIR/usuario/. $USER_HOME/
    cp -r $REPO_DIR/00-keyboard.conf /etc/X11/xorg.conf.d/
    cp -r $REPO_DIR/dake.xml /usr/share/gtksourceview-4/styles/
    cp -r $REPO_DIR/keyboard /etc/default/
    cp -r $REPO_DIR/.config $USER_HOME/
    cp -r $REPO_DIR/Lavender-Breeze-GTK $THEMES_DIR/
    cp -r $REPO_DIR/Infinity-Lavender-Dark-Icons $ICONS_DIR/
    cp -r $REPO_DIR/iconwall.png $WALL_DIR
    cp -r $REPO_DIR/appdesk/. $APPLICATIONS_DIR/
    cp -r $REPO_DIR/fonts/. $FONT_DIR/
    cp -r $REPO_DIR/gtk-3.0 $USER_HOME/.config/
    cp -r $REPO_DIR/fstab $FSTAB_FILE/
    cp -r $REPO_DIR/restorconf.sh $USER_HOME/.local/
   #cp -r $REPO_DIR/.ratpoisonrc $USER_HOME/
   #cp -r $REPO_DIR/bookmarks $USER_HOME/
   #cp -r $REPO_DIR/.gtk-bookmarks $USER_HOME/    
   #cp -r  $REPO_DIR/tilix $FONT_DIR/
   #cp -r  $REPO_DIR/.xinitrc $USER_HOME/
    sleep 2
    clear
}

perm_comun_files() {
    
    # Permisos y Propiedad Para Archivos y Carpetas
    print_status "\n\t\t\t\t PERMISOS Y PROPIEDAD PARA CARPETAS COMUNES CREADAS"
    chown -R $USER:$USER $USER_HOME
    chmod -R 700 $LOCKER_DIR/locker.sh
    chmod -R 600 $LOCKER_DIR/locked.jpg
    # Permisos y Propiedad Carpeta .CONFIG
    chmod -R 700 "$CONFIG_DIR/"
    sleep 2
    clear
}

pass_root_file() {

    print_status "\n\t\t\t\t PASANDO ARCHIVOS A ROOT"
    
    # Creando Una Carpeta .config en root   
    mkdir -pv /root/.config/
    
    # Copia archivos y carpetas de $HOME/.config a /root/.config
    cp -r $REPO_DIR/.config/{bashc,nano,nvim,ranger,zshc,tmux,xres} /root/.config/
    
    # Copia .bashrc a $HOME/root/
    cp -r $REPO_DIR/usuario/.bashrc /root/
    
    # Copia zshenv en /etc/zsh/
    cp -r $REPO_DIR/zshenv /etc/zsh/
    chmod 644 /etc/zsh/zshenv
    sleep 2
    clear
}

poly_ins() {

    print_status "\n\t\t\t\t INSTALANDO POLYBAR"
    
    # Instala "polybar" desde pacman"
    pacman -S --needed polybar --noconfirm
    
    # Instala "polybar-git" desde archivo ".pkg.tar.zst"
    # cd $REPO_DIR/polybar/    
    # pacman -U $POLYBAR_PKG --noconfirm
    sleep 2
    clear
}

ins_logman
ins_browser
check_plugins
create_common_dirs
add_dotfiles
perm_comun_files
pass_root_file
poly_ins

#print_status "*************************"
#print_status "*** REINICIANDO EL PC ***"
#print_status "*************************"
#sleep 1

#reboot
