#!/usr/bin/env bash

# Funciones
function print_status {
    echo -e "\033[1;92m$1\033[0m"
}

if [ "$(id -u)" -eq "0" ]; then
    pacman -Syu --noconfirm
    clear
else
cat << 'EOF'
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
> ███╗░░██╗░█████╗░  ██████╗░░█████╗░░█████╗░████████╗  < 
> ████╗░██║██╔══██╗  ██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝  < 
> ██╔██╗██║██║░░██║  ██████╔╝██║░░██║██║░░██║░░░██║░░░  < 
> ██║╚████║██║░░██║  ██╔══██╗██║░░██║██║░░██║░░░██║░░░  < 
> ██║░╚███║╚█████╔╝  ██║░░██║╚█████╔╝╚█████╔╝░░░██║░░░  < 
> ╚═╝░░╚══╝░╚════╝░  ╚═╝░░╚═╝░╚════╝░░╚════╝░░░░╚═╝░░░  < 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
EOF
sleep 1
clear
exit
fi

USER_HOME="/home/$USER"
FOLD_SHARE="/usr/share"
ICONS_DIR="$FOLD_SHARE/icons/"
THEMES_DIR="$FOLD_SHARE/themes/"
FONT_DIR="$FOLD_SHARE/fonts"
THEME_CUR="Lavender-Breeze-GTK"
ICON_CUR="Infinity-Lavender-Dark-Icons"
REPO_DIR="$USER_HOME/wmarch"
CONFIG_DIR="$USER_HOME/.config"
FSTAB_FILE="/etc/"
LOG_MANA="sddm"

install_displaym() {
    read -p "¿Deseas instalar el display manager $LOG_MANA? (s/n): " respuesta
    if [[ "$respuesta" == "s" || "$respuesta" == "S" ]]; then
        print_status "\n\t\t\t\t INSTALANDO $LOG_MANA"
        pacman -S --needed $LOG_MANA --noconfirm
        systemctl enable $LOG_MANA
        sleep 2
        clear
    else
        print_status "\n\t\t\t\t NO SE INSTALARÁ $LOG_MANA"
        sleep 2
        clear
    fi
}

check_plugins() {
    print_status "\n\t\t\t\t COMPROBANDO PLUGINS DE ZSH"
    if [[ -d $FOLD_SHARE/zsh/plugins/zsh-syntax-highlighting/ && -d $FOLD_SHARE/zsh/plugins/zsh-autosuggestions/ ]]; then
    sleep 2
    clear    
    print_status "\n\t\t\t\t YA EXISTEN LAS CARPETAS DE PLUGINS DE ZSH"
    else
    sleep 2
    clear    
    print_status "\n\t\t\t\t NO EXISTE LA CARPETA DE ZSH"
    sleep 2
    clear    
    print_status "\n\t\t\t INSTALANDO ZSH Y COMPLEMENTOS DE ZSH"
    pacman -S --needed zsh zsh-completions zsh-syntax-highlighting zsh-autosuggestions --noconfirm   
    fi
    sleep 2
    clear
}

create_common_dirs() {
    print_status "\n\t\t\t\t CREANDO CARPETAS COMUNES"
    mkdir -pv $USER_HOME/{desc,plant}
    sleep 2
    clear
}

add_dotfiles() {
    print_status "\n\t\t\t\t AGREGANDO DOTFILES"
    cp -r $REPO_DIR/usuario/. $USER_HOME/
   #cp -r $REPO_DIR/{.ssh,.gitconfig} $USER_HOME/
    cp -r $REPO_DIR/dake.xml /usr/share/gtksourceview-4/styles/
    cp -r $REPO_DIR/.config $USER_HOME/
    cp -r $REPO_DIR/$THEME_CUR $THEMES_DIR/
    cp -r $REPO_DIR/$ICON_CUR $ICONS_DIR/
    cp -r $REPO_DIR/fonts/. $FONT_DIR/
    cp -r $REPO_DIR/fstab $FSTAB_FILE/
    sleep 2
    clear
}

perm_comun_files() {
    print_status "\n\t\t\t\t PERMISOS Y PROPIEDAD PARA CARPETAS COMUNES CREADAS"
    chown -R $USER:$USER $USER_HOME
    chmod -R 700 $CONFIG_DIR/
    sleep 2
    clear
}

pass_root_file() {
    print_status "\n\t\t\t\t PASANDO ARCHIVOS A ROOT"
    mkdir -pv /root/.config/
    cp -r $REPO_DIR/.config/{nano,nvim,zshc,tmux,Xresources} /root/.config/
    cp -r $REPO_DIR/usuario/.bashrc /root/
}

install_displaym
check_plugins
create_common_dirs
add_dotfiles
perm_comun_files
pass_root_file

#print_status "*************************"
#print_status "*** REINICIANDO EL PC ***"
#print_status "*************************"
#sleep 1

#reboot
