#!/usr/bin/env bash

# Funciones De Colores
print_live() {
    echo -e "\033[1;92m$1\033[0m"
}

print_disco() {
    echo -e "\033[1;93m$1\033[0m"
}

print_clone() {
    echo -e "\033[1;95m$1\033[0m"
}

print_error() {
    echo -e "\033[1;91m$1\033[0m"
}

separador() {
sleep 3
clear
}

apt update
apt upgrade

print_live "INSTALANDO DEPENDENCIAS Y PROGRAMAS NECESARIOS"
apt install sudo build-essential curl meson git pkg-config libwayland-dev libxkbcommon-dev libx11-dev libglfw3-dev libcairo2-dev libpango1.0-dev -y
    separador

print_live "APLICACIONES PARA INSTALAR EN HYPRLAND"
apt install psmisc pcmanfm rsync sudo firefox-esr firefox-esr-l10n-es-ar swaybg slurp waybar man-db swaybg zsh zsh-syntax-highlighting zsh-autosuggestions pulseaudio foot wl-clipboard wf-recorder grim mpv bat vifm rofi fzf tmux file-roller lsd gvfs zathura zathura-pdf-poppler nano feh imagemagick fd-find dunst -y
    separador

print_live "AGREGANDO USUARIO SIN PRIVILEGIOS A SUDOERS"
echo "$USER ALL=(ALL:ALL) ALL" >> /etc/sudoers

# print_live "CAMBIANDO BASH POR ZSH"
# SH=zsh
# chsh -s /usr/bin/$SH root
# chsh -s /usr/bin/$SH $USER
#     separador

# print_live "CLONA EL REPOSITORIO DE HYPRLAND"
# git clone --recursive https://github.com/hyprwm/Hyprland /home/$USER/Hyprland
# cd /home/$USER/Hyprland
# print_live "COMPILANDO E INSTALANDO HYPRLAND"
# make install

print_live "INSTALANDO HYPRLAND"
apt install hyprland -y
    separador

print_clone "CREANDO DIR ZSH-COMPLETIONS EN HOME"
mkdir -p /home/$USER/zsh-completions
    separador

print_clone "CLONANDO PLUGIN ZSH-COMPLETIONS"
git clone https://github.com/zsh-users/zsh-completions.git /home/$USER/zsh-completions
    separador

print_clone "COPIANDO DIR SRC Y ZSH-COMPLETIONS.PLUGIN.ZSH EN /USR/SHARE/ZSH-COMPLETIONS"
mkdir -p /usr/share/zsh-completions/
cp -r /home/$USER/zsh-completions/{src,zsh-completions.plugin.zsh} /usr/share/zsh-completions/
    separador

print_clone "BORRANDO ZSH-COMPLETIONS DE HOME"
rm -rf /home/$USER/zsh-completions
    separador

print_clone "CLONANDO REPO WMARCH EN HOME"
git clone -b debhy https://github.com/zafnet/wmarch /home/$USER/wmarch
    separador
print_clone "CAMBIANDO PERMISOS PARA REPO WMARCH EN HOME"
chown -R $USER:$USER /home/$USER/wmarch/
    separador
print_clone "CAMBIANDO PERMISOS PARA DDOTS EN HOME"
chmod 744 /home/$USER/wmarch/ddots
    separador
