[main]
#shell=$SHELL (if set, otherwise user's default shell from /etc/passwd)
#term=foot (or xterm-256color if built with -Dterminfo=disabled)
term=xterm-256color # Para que tome los iconos de utf8 en tmux
#login-shell=no
font=JetbrainsMono Nerd Font:size=12
#app-id=foot # globally set wayland app-id. Default values are "foot" and "footclient" for desktop and server mode
#title=foot
#locked-title=no
#bold-text-in-bright=no # Color en negrita brillante en yes
word-delimiters=,│`|:"'()[]{}<>
#selection-target=primary

[environment]
#name=value

[security]
osc52=enabled  # disabled|copy-enabled|paste-enabled|enabled

[scrollback]
lines=7000
#multiplier=3.0
indicator-position=relative
indicator-format=percentage # Indica el porcentaje del scrollback

[url-bindings]
#cancel=Control+g Control+c Control+d Escape
#cancel=Escape
#toggle-url-visible=Control+Shift+m

[url]
#launch=xdg-open ${url}
#label-letters=sadfjklewcmpgh
#protocols=https,
#osc8-underline=url-mode
#protocols=http, https, ftp, ftps, file, gemini, gopher
#uri-characters=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.,~:;/?#@!$&%*+="'()[]

[cursor]
style=block
#style=underline
#style=beam
#color=<inverse foreground/background>
blink=yes
blink-rate=500
#beam-thickness=1.5
#underline-thickness=<font underline thickness>

[mouse]
hide-when-typing=yes
#alternate-scroll-mode=yes

[touch]
#long-press-delay=400

[colors]
alpha=0.9
#background=262626
#foreground=FFFFFF

## Misc colors
selection-foreground=FF0000        # Color seleccion del mouse tienen que estar las 2
selection-background=F0FF00        # Color seleccion del mouse
search-box-no-match=FF5555 4D4D4D  # Tienen que ir 2 colores para search
search-box-match=5AF78E 4D4D4D     # Tienen que ir 2 colores para search
#jump-labels=FF79C6
#scrollback-indicator=BD93F9
#urls=FF0000

[key-bindings]
scrollback-up-page=Control+Shift+y
scrollback-down-page=Control+Shift+d
#scrollback-up-half-page=none
#scrollback-down-half-page=none
#scrollback-up-line=none
#scrollback-down-line=none
#scrollback-home=none
#scrollback-end=none
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+p XF86Paste
primary-paste=Control+Shift+v
search-start=Control+Shift+s
font-increase=Control+plus
font-decrease=Control+minus
font-reset=Control+0
#show-urls-launch=Control+Shift+o
#show-urls-copy=none
#show-urls-persistent=none
prompt-prev=Control+Shift+z
prompt-next=Control+Shift+x
unicode-input=Control+Shift+u
#noop=none
#quit=none

[search-bindings]
extend-to-word-boundary=none # Deshabilito la tecla C-w para poder setearla para borrar un palabra
delete-to-start=none # Deshabilito la opcion C-u nativa para setearla como scrollback-up-page
#extend-to-word-boundary=Control+w Control+Shift+Right
#cancel=Control+g Control+c Escape
#commit=Return
find-prev=Shift+n   # Buscar anterior en search
find-next=Control+n # Buscar posterior en search
cursor-left=Control+b
cursor-left-word=Mod1+b
cursor-right=Right Control+f
cursor-right-word=Mod1+f
cursor-home=Control+a
cursor-end=Control+e
delete-prev=Control+h
delete-prev-word=Control+w
delete-next=Control+d
delete-next-word=Mod1+d
#extend-char=Shift+Right
#extend-to-next-whitespace=Control+Shift+w
#extend-line-down=Shift+Down
#extend-backward-char=Shift+Left
#extend-backward-to-word-boundary=Control+Shift+Left
#extend-backward-to-next-whitespace=none
#extend-line-up=Shift+Up
#clipboard-paste=Control+v Control+Shift+v Control+y XF86Paste
#primary-paste=Shift+Insert
#unicode-input=none
scrollback-up-page=Control+u
scrollback-down-page=Control+Shift+d
#scrollback-up-half-page=none
#scrollback-up-line=none
#scrollback-down-half-page=none
#scrollback-down-line=none
#scrollback-home=none
#scrollback-end=none

[text-bindings]
#\x03=Mod4+c  # Map Super+c -> Ctrl+c
\x5e = Shift+dead_grave # Para hacer acento ^ presionando shift `

# vim: ft=dosini
