## REGLAS

# Reglas Generales
windowrule = match:class .* , suppress_event maximize

# Reglas discord
windowrule {
  name = discord
  workspace = 6 silent
  match:class = ^(discord)$
}

# Reglas ZapZap
windowrule {
  name = ZapZap
  workspace = 6 silent
  match:class = ^(com.rtosta.zapzap)$
}

# Reglas firefox
windowrule {
  name = float-firefox-library
  match:class = firefox
  match:title = Library
  float = on
}

# Reglas XTerm
windowrule {
  name = opacity-xterm
  match:class = ^(XTerm)$
  opacity = 0.9
}

# Reglas Rofi
# windowrulev2 = float, class:Rofi
# windowrulev2 = bordersize 0,class:Rofi 

# Reglas mpv
windowrule = match:class ^(mpv)$, float on
windowrule = match:class ^(mpv)$, size 725 613
windowrule = match:class ^(mpv)$, move 60% 16%

# Reglas cmus
windowrule = match:title ^(com\.cmus)$, float on
windowrule = match:title ^(com\.cmus)$, size 725 613
windowrule = match:title ^(com\.cmus)$, move 60% 16%

# Reglas upda_term de SO en waybar con foot
windowrule = match:title ^(upda_term)$, float on
windowrule = match:title ^(upda_term)$, center on
windowrule = match:title ^(upda_term)$, size 725 613
#windowrule = match:title ^(upda_term)$, move 60% 16%
#windowrule = match:title ^(upda_term)$, workspace 6, follow

# Reglas para File Roller
windowrule = match:class ^(org\.gnome\.FileRoller)$, float on
windowrule = match:class ^(org\.gnome\.FileRoller)$, size 725 613
windowrule = match:class ^(org\.gnome\.FileRoller)$, move 60% 16%
