## REGLAS

# Reglas Generales
windowrulev2 = suppressevent maximize, class:.*

# Reglas discord
windowrulev2 = workspace 5 silent,class:^discord$

# Reglas firefox
windowrulev2 = float,class:(firefox),title:(Library)

# Reglas XTerm
windowrulev2 = opacity 0.9,class:^(XTerm)$

# Reglas Rofi
windowrule = float, class:Rofi
windowrulev2 = bordersize 0,class:Rofi 

# Reglas mpv
windowrulev2 = float,class:^(mpv)$
windowrulev2 = size 725 613,class:^(mpv)$
windowrulev2 = move 60% 16%,class:^(mpv)$

# Reglas cmus
windowrulev2 = float,title:^(com.cmus)$
windowrulev2 = size 725 613,title:^(com.cmus)$
windowrulev2 = move 60% 16%,title:^(com.cmus)$

# Reglas upda_term de SO en waybar con foot
windowrulev2 = float,title:^(upda_term)$
windowrulev2 = center,title:^(upda_term)$
windowrulev2 = size 725 613,title:^(upda_term)$
#windowrulev2 = move 60% 16%,title:^(upda_term)$
#windowrulev2 = workspace 6,follow,title:^(upda_term)$

# Reglas file-roller
windowrulev2 = float,class:^(org.gnome.FileRoller)$
windowrulev2 = size 725 613,class:^(org.gnome.FileRoller)$
windowrulev2 = move 60% 16%,class:^(org.gnome.FileRoller)$
