# Backend
backend = "xrender";
#backend = "glx";
#vsync = "none";
#paint-on-overlay = true;
#mark-wmwin-focused = true;
#unredir-if-possible = true;
detect-rounded-corners = true;

# Shadow
#shadow = true;
shadow-radius = 10;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.40;
shadow-ignore-shaped = true;

# Opacity
active-opacity = 0.90;
inactive-opacity = 0.85;
frame-opacity = 0.80;


opacity-rule = [
	"50:class_g = 'Bspwm' && class_i = 'presel_feedback'",
	"88:class_g = 'Rofi'",
	"98:class_g = 'Pcmanfm'",
    "100:class_g = 'Google-chrome'",
    "100:class_g = 'firefox'",
    "100:class_g = 'discord'",
    "100:class_g = 'VirtualBox Manager'",
    "100:class_g = 'Xed'",
    "100:class_g = 'VirtualBox Machine'",
	"99:class_g = 'burp-StartBurp'",
   "99:class_g = 'Zathura'" 

];

#blur-background = true;

# Fade
fading = true;
fade-delta = 2;
fade-in-step = 0.03;
fade-out-step = 0.028;
no-fading-openclose = true;
no-fading-destroyed-argb = false;

shadow-exclude = [
    # "x <= 3 && x2 >= 1360",
    # "y <= 27 && y2 >= 740",
    "name *?= 'Notification'",
    #"class_g *?= 'jgmenu'",
    "class_g *?= 'VirtualBox'",
    "class_g *?= 'Conky'",
    "class_g *?= 'Dunst'",
    "class_g *?= 'Notify-osd'",
    "class_g *?= 'cairo-dock'",
    "class_g *?= 'trayer'",
    "class_g *?= 'stalonetray'",
    "class_g *?= 'i3-frame'",
    "class_g *?= 'Chromium'",
    "class_g *?= 'Firefox' && argb",
    "class_g *?= 'navigator'",
    "class_g *?= 'Cairo-clock'",
    "class_g *?= 'Cairo-dock'",
    "class_g *?= 'plank'",
    "class_g *?= 'skippy-xd'",
    "class_g *?= 'Atom'",
    "class_g *?= 'Docky'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "_GTK_FRAME_EXTENTS@:c"
];

focus-exclude = [
    "class_g *?= 'Cairo-clock'",
    "class_g *?= 'Virtualbox'",
    "class_g *?= 'stalonetray'",
    "class_g *?= 'trayer'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "name *?= 'Authy'"
];

wintypes:
{
    tooltip =
    {
        # fade: Fade the particular type of windows.
        fade = true;
        # shadow: Give those windows shadow
        shadow = true;
        # opacity: Default opacity for the type of windows.
        opacity = 0.85;
        # focus: Whether to always consider windows of this type focused.
        focus = true;
    };
};
