#!/usr/bin/env bash
#██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

pgrep -x sxhkd > /dev/null || sxhkd &     # Verificando Si sxhkd Se Lanzo Si No Lanzarlo
dunst &
picom -b --config $HOME/.config/picom/picom.conf         # Picom Ruta Custom En El Back
exec /home/$USER/.config/polybar/launch.sh  &            # Lanzando Polybar
feh --bg-fill --randomize --no-fehbg /home/$USER/.wall/* # Lanzando Wallpaper

# 5 Escritorios En Varios Monitores
bspc monitor  HDMI-1 -d       
#bspc monitor DVI-1 -d         
#bspc monitor DVI-D-1 -d I II III IV V
#bspc monitor DP-1 -d 1 2 3 4 5
#bspc monitor DP-2 -d            

# Configuracion Bspwm
bspc config ignore_ewmh_focus true
bspc config border_width                  1
bspc config window_gap                    7
bspc config top_padding                   23
bspc config bottom_padding                -4
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                button1
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_follows_pointer         false
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config initial_polarity second_child
#bspc config initial_polarity first_child
#bspc config automatic_scheme spiral

# Color De Borde De Ventana
#bspc config normal_border_color		  "#ff0000"
#bspc config active_border_color	      "#fafb4e"
bspc config focused_border_color	      "#77f28b"
bspc config presel_feedback_color	      "#ffe6a7"
#bspc config urgent_border_color          "#ff0000"

# Reglas 
bspc rule -a '*:xterm' border=off
bspc rule -a TelegramDesktop desktop='^5' follow=off
bspc rule -a discord desktop='^5' follow=off
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Galculator state=floating
bspc rule -a polybar manage=off
#bspc rule -a firefox desktop='^1' follow=off
#bspc rule -a mpv state=floating sticky=on rectangle=300x180+1060+475 center=on
