#!/usr/bin/env bash
#██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

#-- Autoarranque

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -v es
dunst &
picom &
exec /home/$USER/.config/polybar/launch.sh  &

#feh --bg-fill --randomize --no-fehbg /home/$USER/.wall/*
bash /home/$USER/.local/wallrandom.sh & 

#-- Esc Por Mayus
setxkbmap -option "caps:swapescape"

#-- Polybar En Varios Monitores Con Salida DisplayPort o HDMI

#bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
#bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

#-- 5 Iconos En El Monitor

#bspc monitor -d  1 2 3 4 5 
bspc monitor  -d          
#bspc monitor -d  I II III IV V

#-- 6 Iconos En El Monitor

#bspc monitor -d  1 2 3 4 5 6
#bspc monitor -d             
#bspc monitor -d  I II III IV V VI

#-- 10 Iconos En El Monitor

#bspc monitor -d  1 2 3 4 5 6 7 8 9 10
#bspc monitor -d  I II III IV V VI VII VIII IX X
#bspc monitor -d                   

#-- Configuracion Bspwm

bspc config border_width                  3
bspc config window_gap                    10
bspc config top_padding                   39
bspc config bottom_padding                1
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                none
bspc config split_ratio                   0.52
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#-- Color De Borde De Ventana


bspc config normal_border_color		      "#ff0000"
bspc config active_border_color	          "#fafb4e"
bspc config focused_border_color	      "#77f28b"
bspc config presel_feedback_color	      "#ffe6a7"
#bspc config urgent_border_color          "#ff0000"

#bspc config normal_border_color	      "#faa608"
#bspc config active_border_color          "#fafb4e"
#bspc config focused_border_color	      "#9406f7"
#bspc config presel_feedback_color	      "#77f28b"
#bspc config urgent_border_color          "#ff0000"

#-- Reglas Modo En Que Van a Aparecer Las Ventanas En El Escritorio

bspc rule -a TelegramDesktop desktop='^5' follow=on
bspc rule -a discord desktop='^5' follow=on
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Galculator state=floating
bspc rule -a polybar manage=off
#bspc rule -a mpv state=floating sticky=on rectangle=300x180+1060+475 center=on
