-- COLOR PARA GUI MOXI
vim.g.colors_name = 'moxi'

-- Función auxiliar para establecer colores
local hi = function(group, properties)
  vim.api.nvim_set_hl(0, group, properties)
end

 hi ("Normal",{ fg="#ff8700",bg="#262626" ,bold=true})
 hi ("Cursor",{ fg="#ff0000",bg="NONE" ,bold=true})
 hi ("CursorLine",{ fg="NONE",bg="NONE" ,bold=true})
 hi ("CursorLineFold",{ fg="#d75f87",bg="NONE" ,bold=true})
   --hi ("cursorlinesign",{ fg="#af0000", bg="NONE", bold=true})
   --hi ("cursorlinenr",{ fg="NONE",bg="none", bold=none })
   --hi ("linenrabove",{ fg="NONE",bg="none" ,bold=none})
   --hi ("linenrbelow",{  fg="NONE",bg="none" ,bold=none})
   --hi ("define",{ fg="#00ffff", bg="#3a3a3a" ,bold=true})
 hi ("CurSearch",{ fg="#ffaf00",bg="#3a3a3a" ,bold=true})
 hi ("IncSearch",{ fg="#00af00",bg="#262626" ,bold=true})
 hi ("Folded",{ fg="#00005f",bg="#d7d7d7" ,bold=true})
 hi ("Search",{ fg="#ff5faf",bg="#3a3a3a" ,bold=true})
 hi ("LineNr",{ fg="#005f87",bg="#444444" ,bold=true})
 hi ("Directory",{ fg="#005faf",bg="NONE" ,bold=true})
 hi ("MatchParen",{ fg="#ff0000",bg="NONE" ,bold=true})
 hi ("ModeMsg",{ fg="#005f87",bg="#000000" ,bold=true})
 hi ("MsgArea",{ fg="#005f87",bg="#3a3a3a" ,bold=true})
 hi ("Pmenu",{ fg="#d75f87",bg="#3a3a3a" ,bold=true})
 hi ("PmenuSel",{ fg="#d75f87",bg="#262626" ,bold=true})
 hi ("PmenuSbar",{ fg="#d75f87",bg="#3a3a3a" ,bold=true})
 hi ("Question",{ fg="#ff87af",bg="#3a3a3a" ,bold=true})
 hi ("WarningMsg",{ fg="#ff0000",bg="#2e2e2e" ,bold=true})
 hi ("Title",{ fg="#5faf87",bg="NONE" ,bold=true})
 hi ("Visual",{ fg="NONE",bg="#3a3a3a" ,bold=true})
 hi ("VisualNOS",{ fg="NONE",bg="#005f87" ,bold=true})
 hi ("Comment",{ fg="#b2b2b2",bg="NONE" ,bold=true})
 hi ("String",{ fg="#ff5f5f",bg="NONE" ,bold=true})
 hi ("Character",{ fg="#d787af",bg="NONE" ,bold=true})
 hi ("Number",{ fg="#ff8700",bg="NONE" ,bold=true})
 hi ("Boolean",{ fg="#800080",bg="NONE" ,bold=true})
 hi ("Float",{ fg="#800080",bg="NONE" ,bold=true})
 hi ("Identifier",{ fg="#00af5f",bg="NONE" ,bold=true})
 hi ("Function",{ fg="#ffff5f",bg="NONE" ,bold=true})
 hi ("Statement",{ fg="#d7005f",bg="NONE" ,bold=true})
 hi ("Conditional",{ fg="#d75f87",bg="NONE" ,bold=true})
 hi ("Repeat",{ fg="#d70000",bg="NONE" ,bold=true})
 hi ("Label",{ fg="NONE",bg="NONE" ,bold=true})
 hi ("Operator",{ fg="#ffd7af",bg="NONE" ,bold=true})
 hi ("Keyword",{ fg="#ff5f5f",bg="NONE" ,bold=true})
 hi ("Exception",{ fg="#ff0000",bg="NONE" ,bold=true})
 hi ("Special",{ fg="#ff8700",bg="NONE" ,bold=true})
 hi ("SpecialComment",{ fg="#ffafd7",bg="NONE" ,bold=true})
 hi ("SpecialKey",{ fg="#ff5f5f",bg="NONE" ,bold=true})
 hi ("trued",{ fg="#5faf5f",bg="NONE" ,bold=true})
 hi ("VertSplit",{ fg="#00af87",bg="NONE" ,bold=true})
 hi ("FoldColumn",{ fg="#00005f",bg="NONE" ,bold=NONE})
 hi ("ErrorMsg",{ fg="#ff0000",bg="#ffd7af" ,bold=true})
 hi ("Error",{ fg="#ff0000",bg="#ffffff" ,bold=true})
 hi ("DiffAdd",{ fg="#87d7af",bg="NONE" ,bold=true})
 hi ("DiffChange",{ fg="#ff0000",bg="NONE" ,bold=true})
 hi ("DiffText",{ fg="#ffd7af",bg="NONE" ,bold=true})
 hi ("DiffDelete",{ fg="#ff0000",bg="none" ,bold=true})
 hi ("Debug",{ fg="NONE",bg=NONE ,bold=true})
 hi ("EndOfBuffer",{ fg="#af00af",bg="NONE" ,bold=true})
 hi ("Terminal",{ fg="#87d7af",bg="NONE" ,bold=true})
 hi ("SignColumn",{ fg="#ff0000",bg="NONE" ,bold=true})
 hi ("MoreMsg",{ fg="#00af5f",bg="NONE" ,bold=true})
  --hi ("wildmenu",{ fg="#000000", bg="#ffff00" , bold=true})
  --hi ("cursorcolumn",{ fg="NONE",bg="#d0d0d0" ,bold=none})
  --hi ("tabline",{ fg="#000000" ,bg="#bcbcbc" , bold=true})
  --hi ("tablinefill",{ fg="NONE",bg="none" ,  bold=true})
  --hi ("tablinesel",{ fg="#000000", bg="#e4e4e4", bold=true})
  --hi ("toolbarline",{ fg="NONE",bg="none", bold=none})
  --hi ("toolbarbutton",{ fg="NONE",bg="#bcbcbc", bold=true})
  --hi ("nontext",{ fg="#0000ff" ,bg="#bcbcbc" ,bold=true})
  --hi ("statuslinetermnc",{ fg="#ffff00", bg="#444444", bold=true})
  --hi ("statuslineterm",{ fg="#ffff00" ,bg="#444444" ,bold=true})
 hi ("Type",{ fg="#ffd700",bg="NONE" ,bold=true})
 hi ("MessageWindow",{ fg="#8700af",bg="NONE" ,bold=true})
 hi ("PopupNotification",{ fg="#8700af",bg="#2e2e2e" ,bold=true})
 hi ("TabLine",{ fg="#000000",bg="#d7d7d7" ,bold=true})
 hi ("TabLineFill",{ fg="NONE",bg=NONE ,bold=true})
 hi ("TabLineSel",{ fg="#000000",bg="#ffffff" ,bold=true})
 hi ("ToolbarLine",{ fg="NONE",bg=NONE ,bold=true})
 hi ("ToolbarButton",{ fg="NONE",bg="#d7d7d7" ,bold=true})
 hi ("ColorColumn",{ fg="#800080",bg="#ffffff" ,bold=true})
 hi ("SpellBad",{ fg="#ff0000",bg="NONE" ,bold=true})
 hi ("SpellCap",{ fg="#00af00",bg="NONE" ,bold=true})
 hi ("SpellLocal",{ fg="#d70000",bg="NONE" ,bold=true})
 hi ("SpellRare",{ fg="#00af5f",bg="NONE" ,bold=true})
