-- Color para gui saxs

-- Establece el nombre de los colores
vim.g.colors_name = 'saxs'

-- Función auxiliar para establecer colores
local hi = function(group, properties)
  vim.api.nvim_set_hl(0, group, properties)
end

-- Configuraciones de colores
hi("Normal", { fg = "NONE", bg = "NONE", bold = true })
hi("Cursor", { fg = "#ff0000", bg = "NONE", bold = true })
hi("CursorLine", { fg = "NONE", bg = "#444444", bold = false })
hi("CurSearch", { fg = "#ffaf00", bg = "#3a3a3a", bold = true })
hi("CursorLineFold", { fg = "#ff5f5f", bg = "NONE", bold = true })
hi("Folded", { fg = "#00af5f", bg = "#3a3a3a", bold = false })
hi("IncSearch", { fg = "#ffaf00", bg = "#3a3a3a", bold = true })
hi("Search", { fg = "#ff5faf", bg = "#3a3a3a", bold = true })
hi("LineNr", { fg = "#ff5f5f", bg = "#444444", bold = true })
hi("MatchParen", { fg = "#ff0000", bg = "NONE", bold = true })
hi("ModeMsg", { fg = "#ff5f5f", bg = "#000000", bold = true })
hi("MsgArea", { fg = "#ff5f5f", bg = "#3a3a3a", bold = true })
hi("Pmenu", { fg = "#ff5f5f", bg = "#3a3a3a", bold = true })
hi("PmenuSel", { fg = "#ff5f5f", bg = "#262626", bold = true })
hi("PmenuSbar", { fg = "#ff5f5f", bg = "#3a3a3a", bold = true })
hi("Question", { fg = "#ff87af", bg = "#3a3a3a", bold = true })
hi("WarningMsg", { fg = "#ffd700", bg = "#2e2e2e", bold = true })
hi("StatusLineTerm", { fg = "#005f87", bg = "NONE", bold = false })
hi("Title", { fg = "#5faf87", bg = "NONE", bold = true })
hi("Visual", { fg = "NONE", bg = "#3a3a3a", bold = true })
hi("VisualNOS", { fg = "NONE", bg = "#005f87", bold = false })
hi("Comment", { fg = "#b2b2b2", bg = "NONE", bold = true })
hi("String", { fg = "#ffd700", bg = "NONE", bold = true })
hi("Character", { fg = "#d787af", bg = "NONE", bold = true })
hi("Number", { fg = "#ff8700", bg = "NONE", bold = true })
hi("Boolean", { fg = "#800080", bg = "NONE", bold = true })
hi("Float", { fg = "#800080", bg = "NONE", bold = true })
hi("Identifier", { fg = "#00af5f", bg = "NONE", bold = true })
hi("Function", { fg = "#87ff87", bg = "NONE", bold = true })
hi("Statement", { fg = "#d7005f", bg = "NONE", bold = true })
hi("Conditional", { fg = "#ff5f5f", bg = "NONE", bold = true })
hi("Repeat", { fg = "#d70000", bg = "NONE", bold = true })
hi("Label", { fg = "NONE", bg = "NONE", bold = true })
hi("Operator", { fg = "#ffd7af", bg = "NONE", bold = true })
hi("Keyword", { fg = "#ff5f5f", bg = "NONE", bold = true })
hi("Exception", { fg = "#ff0000", bg = "NONE", bold = true })
hi("Special", { fg = "#af87af", bg = "NONE", bold = true })
hi("SpecialComment", { fg = "#8700af", bg = "NONE", bold = true })
hi("SpecialKey", { fg = "#ff5f5f", bg = "NONE", bold = true })
hi("Underlined", { fg = "#00ff87", bg = "NONE", bold = true })
hi("VertSplit", { fg = "#00af87", bg = "NONE", bold = true })
hi("FoldColumn", { fg = "#00005f", bg = "NONE", bold = false })
hi("ErrorMsg", { fg = "#ff0000", bg = "#ffd7af", reverse = true })
hi("Error", { fg = "#ff0000", bg = "#ffffff", reverse = true })
hi("DiffAdd", { fg = "#87d7af", bg = "NONE", bold = false })
hi("DiffChange", { fg = "#ff0000", bg = "NONE", bold = false })
hi("DiffText", { fg = "#ffd7af", bg = "NONE", bold = false })
hi("DiffDelete", { fg = "#ff0000", bg = "NONE", bold = false })
hi("Debug", { fg = "NONE", bg = "NONE", bold = true })
hi("EndOfBuffer", { fg = "#af00af", bg = "NONE", bold = true })
hi("Terminal", { fg = "#87d7af", bg = "NONE", bold = true })
hi("SignColumn", { fg = "#ff0000", bg = "NONE", bold = false })
hi("MoreMsg", { fg = "#00af5f", bg = "NONE", bold = true })
hi("StatuslineTermNC", { fg = "#ffd700", bg = "#444444", bold = true })
hi("Type", { fg = "#ffd700", bg = "NONE", bold = true })
hi("MessageWindow", { fg = "#8700af", bg = "NONE", bold = true })
hi("PopupNotification", { fg = "#8700af", bg = "#2e2e2e", bold = true })
hi("ToolbarLine", { fg = "NONE", bg = "NONE", bold = false })
hi("ToolbarButton", { fg = "NONE", bg = "#d7d7d7", bold = true })
hi("ColorColumn", { fg = "#800080", bg = "#ffffff", bold = false })
hi("SpellBad", { fg = "#ff0000", bg = "NONE", underline = true })
hi("SpellCap", { fg = "#00d700", bg = "NONE", underline = true })
hi("SpellLocal", { fg = "#d70000", bg = "NONE", underline = true })
hi("SpellRare", { fg = "#00af5f", bg = "NONE", underline = true })
hi("TabLine", { fg = "#444444", bg = "#af87af", bold = true })
hi("TabLineFill", { fg = "#444444", bg = "NONE", bold = true })
hi("TabLineSel", { fg = "#444444", bg = "#00af5f", bold = true })
