#   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
#   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
#   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
#   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
#   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
#   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝

#---------#
# BARRA 1 #
#---------#
[bar/principal]
monitor = HDMI-1
;monitor-fallback = HDMI1
width = 27%
height = 30
offset-x = 38%
offset-y = 1%
radius = 12%
fixed-center = false
bottom = false
;separator = 
background = #6c605e
##5b8075
#foreground = #ff0000
line-size = 1
;line-color = 0
wm-restack = bspwm
override-redirect = true
enable-ipc = true
;border-size = 0
;border-left-size = 0
;border-right-size = 0
;border-top-size = 0
;border-bottom-size = 0
;border-color = #00000000
padding-left = 0
padding-right = 3
module-margin-left = 2
module-margin-right = 0
#tray-position = right
#tray-detached = false
#tray-maxsize = 2
#tray-offset-x = -0.1
#tray-padding = 4
#tray-transparent = false
modules-left =
modules-center = bspwm
modules-right =
#modules-left =memory cpu updates xwindow
#modules-center = bspwm
#modules-right = pulseaudio fecha
scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

#----------------#
# FONTS CARGADAS #
#----------------#
font-0 = "UbuntuMono Nerd Font:size=10;2"
font-1 = "UbuntuMono Nerd Font:size=16;3"
#font-2 = "Font Awesome 5 Free:style=Regular:pixelsize=8;1"
#font-3 = "Font Awesome 5 Free:style=Solid:pixelsize=8;1"
font-4 = "Font Awesome 5 Brands:pixelsize=8;1"
#font-0 = "fixed:pixelsize=10;1"
#font-1 = "unifont:fontformat=truetype:size=8:antialias=false;0"
font-5 = "Hack Nerd Font Mono:pixelsize=8;1"
font-6 =  "PowerlineSymbols:pixelsize=8;1"
#font-4 = "siji:pixelsize=10;1"

#---------#
# BARRA 2 #
#---------#

[bar/repro]
inherit = bar/principal
monitor = HDMI-1
#monitor-fallback = HDMI1
width = 10.5%
height = 30
offset-x = 1%
offset-y = 1%
radius = 10%
fixed-center = false
bottom = false
separator =
background = #6c605e
#5b8075
#foreground = #ff0000
;line-size = 0
;line-color = 0
wm-restack = bspwm
override-redirect = false
;border-size = 0
;border-left-size = 0
;border-right-size = 0
;border-top-size = 0
;border-bottom-size = 0
#border-color = #00000000
padding-left = 1
padding-right = 0
module-margin-left = 0
module-margin-right = 3
modules-left = updates memory cpu
modules-center =
modules-right = 

#---------#
# BARRA 3 #
#---------#

[bar/derecha]
inherit = bar/principal
monitor = HDMI-1
#monitor-fallback = HDMI1
width = 15%
height = 30
offset-x = 84%
offset-y = 1%
radius = 10%
fixed-center = true
bottom = false
separator =
background = #6c605e
#5b8075
#foreground = #ff0000
;line-size = 0
;line-color = 0
wm-restack = bspwm
override-redirect = true
;border-size = 0
;border-left-size = 0
;border-right-size = 0
;border-top-size = 0
;border-bottom-size = 0
#border-color = #00000000
padding-left = 0
padding-right = 4
module-margin-left = 0
module-margin-right = 2
modules-left =
modules-center = pulseaudio fecha
modules-right = 

#----------------#
# MODULO BSPWM   # 
#----------------#
[module/bspwm]
type = internal/bspwm
enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true
 
#ws-icon-0 = 1;%{F#COLORHEXA}
#ws-icon-1 = 2;
#ws-icon-2 = 3;
#ws-icon-3 = 4;
#ws-icon-4 = 5;
#ws-icon-5 = 6;
#ws-icon-6 = 7;
#ws-icon-7 = 8;
#ws-icon-8 = 9;
#ws-icon-9 = 10;
#ws-icon-default = " "

#---------------------------------------------#
# ICONOS PARA ESCRITORIO ENFOCADO OCUPADO ETC #
#---------------------------------------------#
format = <label-state> <label-mode>
#ACA PARA QUE SE VEAN LOS ICONOS DE ARRIBA AL LABEL-FOCUSED HAY QUE PONERLE label-focused = %icon%
label-focused = 
#label-focused-background = 
#label-focused-underline = #98FB98
label-focused-padding = 2
label-focused-foreground =#ffa500

label-occupied = 
label-occupied-padding = 2
label-occupied-underline=
label-occupied-background =
label-occupied-foreground = #dc143c

label-empty = 
#
label-empty-foreground = #00cc99
#fe00f3 
##ff1493
label-empty-padding = 2
#label-empty-background = 
label-monocle = "  "
#label-monocle-foreground = 
#label-tiled = "  "
#label-tiled-foreground = 
#label-fullscreen = "  "
label-fullscreen-foreground = 
label-floating = "  "
label-floating-foreground = 
#label-pseudotiled = "  "
label-pseudotiled-foreground = 
label-locked = " "
label-locked-foreground = 
#label-sticky = "  "
label-sticky-foreground = 
#label-private =  "     "
label-private-foreground = 
;SEPARADOR ENTRE ESPACIOS DE TRABAJO
#label-separator = 
#label-separator-padding = 40
#label-separator-foreground = #fb7760
#format-foreground = #c5fd27
#format-background = #c5fd27

#-----------------#
# MODULOS COMUNES #
#-----------------#
#[module/date]
#type = internal/date
#interval = 5
#date = " %a %b %d, %Y"
#date-alt = " %a %b %d, %Y"
#time = %l:%M%p
#time-alt = %l:%M%p
#format-prefix = " "
#format-prefix-foreground = #fefefe
#format-foreground = #fefefezzzzz
#format-background = #668bd7
#label = "%date% %time% "

[module/cpu]
type = internal/cpu
; Seconds to sleep between updates
; Default: 1
interval = 1
format-foreground = #27edc9
#format-background = #099a8e
format-prefix ="﬙ "
format-prefix-foreground = #7efe88
label-font = 1
; Available tags:
;   <label> (default)
;   <bar-load>
;   <ramp-load>
;   <ramp-coreload>
format = <label>
; Available tokens:
;   %percentage% (default) - total cpu load
;   %percentage-cores% - load percentage for each core
;   %percentage-core[1-9]% - load percentage for specific core
label = 3%


[module/pulseaudio]
type = internal/pulseaudio
format-volume = "  <label-volume>"
format-muted = "ﱝ  MUDO"
label-volume = %percentage%%
label-muted = %percentage%%
#label-volume-foreground = ${colors.color4} 
label-volume-background = 
label-muted-foreground = #ff0000
label-muted-background = 
format-volume-foreground = #00ff00	
#format-volume-background = #ef891e
format-muted-foreground =  #ff0000
format-muted-background = #ef891e 


[module/memory]
type = internal/memory
interval = 1
; Available tokens:
;   %percentage_used% (default)
;   %percentage_free%
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
label = %percentage_used%%
format =<label>
format-prefix ="   "
format-prefix-foreground = #f9ff00
format-foreground = #f9ff00
#format-background = #ef891e


[module/xwindow]
type = internal/xwindow
;ETIQUETAS DISPONIBLES
;<label> (Default) 
;TOKENS DISPONIBLES
;%title%
label = %title%
label-maxlen = 50
format-prefix ="   "
format-prefix-underline = #ff0080 
format-underline = #ff0080
format-overline = #ff0080
format = <label>
format-foreground = #4fff33
format-background = #808b96
###669999
##999999
##e2f8dab1
format-padding =
#label-empty = 
#label-empty-foreground = 

#--------------------#
# INTERNET CONECTADO #
#--------------------#
#[module/eth]
#type = internal/network
#interface = enp37s0
#label-connected = UP
#label-connected-foreground = #00ff08
#format-connected = <label-connected>
#format-connected-prefix ="   "
#format-connected-prefix-foreground = #00ff00
#format-connected-foreground = #fefefe
#format-connected-background = #099a8e
#format-connected-underline = #55aa55
#-----------------------#
# INTERNET DESCONECTADO #
#-----------------------#
#label-disconnected = DOWN
#label-disconnected-foreground = #ff0000
#format-disconnected =
#format-disconnected-prefix = "  "
#format-disconnected-prefix-foreground = #ff0000
#format-disconnected-foreground = #fefefe
#format-disconnected-background = #099a8e
#format-disconnected-underline = #55aa55

#-----------------#
# MODULOS COSTOM  #
#-----------------#

[module/fecha]
type = custom/script
exec = ~/.config/polybar/scripts/fecha
interval = 5
format-prefix ="   "
format-prefix-foreground = #c1ff00
format-foreground = #c1ff00
#format-background = #ef891e
label =%output%

#[module/fechaalt]
#type = custom/script
#exec = ~/.config/polybar/scripts/fechaalt
#format-prefix ="   "
#format-prefix-foreground = #c1ff00
#format-foreground = #c1ff00
#format-background = #ef891e
#click-left = ~/.config/polybar/scripts/fechaalt
#label =%output%

[module/updates]
type = custom/script
exec = checkupdates | wc -l
interval = 5
format-prefix = "  "
#plantillaformat-prefix = "   "
format-prefix-foreground = #ffae42  
format-foreground =#00ffb3
#format-background =#099a8e
label =%output%

#-----------------------#
# NO USADOS POR AHORA   #
#-----------------------#

[module/mpd]
type = internal/mpd
;format-online =  "<label-song>   <icon-prev>  <icon-stop>  <toggle>  <icon-next>"
format-online =  "<label-song>  <bar-progress>"
;format-online =  "<label-song>  <bar-progress> <icon-prev>  <icon-stop>  <toggle>  <icon-next>"
icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
label-song-maxlen = 40
label-song-ellipsis = true
bar-progress-width = 10
bar-progress-indicator = 
bar-progress-fill = 
bar-progress-empty = 
bar-progress-fill-foreground = #ff0
bar-progress-fill-background = 
bar-progress-indicator-foreground = 
format-online-foreground = 
format-online-background = 


[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight
format-foreground = 
format-background = 
format-prefix-foreground = #7D49B6
format-prefix-underline = #7D49B6
format-underline = #7D49B6


[module/backlight]
type = internal/backlight
; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight
; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <label>
format-foreground = 
format-background = 
; Available tokens:
;   %percentage% (default)
label = %percentage%%
; Only applies if <ramp> is used
ramp-0 = 🌕
ramp-1 = 🌔
ramp-2 = 🌓
ramp-3 = 🌒
ramp-4 = 🌑
; Only applies if <bar> is used
bar-width = 10
bar-indicator = |
bar-fill = ─
bar-empty = ─ 


;[module/sep]
;type = custom/text
;content = 
;content-foreground = 
;content-background =  
;format-foreground = 
;format-background = 


[module/temp]
type = internal/temperature
; Thermal zone to use
; To list all the zone types, run
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 0
; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; Default reverts to thermal zone setting
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input
warn-temperature = 70
format = <ramp> <label>
format-foreground = 
format-background = 
format-underline = #c72581
format-warn = <ramp> <label-warn>
format-warn-underline = #c7254f
label = %temperature%
label-warn =  %temperature%
label-warn-foreground = #c7254f
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-foreground =


[module/wireless-network]
type = internal/network
interface = ${env:WIRELESS}
interval = 3.0
label-connected = %essid%
format-connected = <label-connected>
;format-connected = <ramp-signal> <label-connected>
format-connected-foreground = 
format-connected-background = 
format-connected-prefix = "  "
format-connected-prefix-foreground = #7e52c6
format-connected-prefix-background = 
format-connected-underline = #7e52c6
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.alert}
label-disconnected-background = 
format-disconnected = <label-disconnected>
format-disconnected-foreground = ${colors.alert}
format-disconnected-background = 
format-disconnected-prefix = "  "
format-disconnected-prefix-foreground = ${colors.alert}
format-disconnected-prefix-background = 
format-disconnected-underline =${colors.alert}
ramp-signal-0 = ▁
ramp-signal-1 = ▂
ramp-signal-2 = ▃
ramp-signal-3 = ▄
ramp-signal-4 = ▅
ramp-signal-5 = ▆
ramp-signal-6 = ▇
ramp-signal-7 = █
ramp-signal-foreground = #7e52c6


[module/xbacklight]
type = internal/xbacklight
format = <label> <bar>
format-prefix = "   "
#format-prefix-foreground = 
#format-prefix-background = 
format-prefix-underline = #9f78e1
format-underline = #9f78e1
label = %percentage%%
bar-width = 10
bar-indicator = 
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = 
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = 
bar-empty-font = 2
bar-empty-foreground = #fff
#format-foreground = 
#format-background = 


[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
format-prefix = " "
format-prefix-foreground = 
format-prefix-background = 
format-prefix-underline = #3ecfb2
format-foreground = 
format-background = 
label-layout = %layout%
label-layout-underline = #3ecfb2
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = 
label-indicator-underline = 

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC0
full-at = 100
format-charging = <animation-charging> <label-charging>
label-charging =  %percentage%%
format-charging-foreground = 
format-charging-background = 
format-charging-underline = #a3c725
format-discharging = <ramp-capacity> <label-discharging>
label-discharging =  %percentage%%
format-discharging-underline = #c7ae25
format-discharging-foreground = 
format-discharging-background = 
format-full-prefix = " "
format-full-prefix-foreground = #a3c725
format-full-underline = #a3c725
format-full-foreground = 
format-full-background = 
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = #c7ae25
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = #a3c725
animation-charging-framerate = 750
#pseudo-transparency = false
